# development: &default
#   adapter: postgresql
#   database: ruidos_development
#   encoding: utf8
#   host: localhost
#   min_messages: warning
#   pool: <%= ENV.fetch("DB_POOL", 5) %>
#   reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>
#   timeout: 5000

# test:
#   <<: *default
#   database: ruidos_test

# production: &deploy
#   encoding: utf8
#   min_messages: warning
#   pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>
#   timeout: 5000
#   url:  <%= ENV.fetch("DATABASE_URL", "") %>

# staging: *deploy


development:
  adapter: postgresql
  encoding: unicode
  database: fazinova_dois
  pool: 5
  username: postgres
  password: 1234
  port:  5433
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: fazinova_dois
  pool: 5
  username: postgres
  password: 1234
  port:  5433
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: fazinova_dois
  pool: 5
  username: postgres
  password: 1234
  host: localhost