default: &default
 secret_key_base: 52ac86b6fe8faa17fac89181438092f7e0e5c4c78bf22fa1121a0a541d3c4c0f71004ac04fc8d03511b9770e3c220ed5f17eaac7ee4fc01805c1eff3b91b2576
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default


# # Be sure to restart your server when you modify this file.

# # Your secret key is used for verifying the integrity of signed cookies.
# # If you change this key, all old signed cookies will become invalid!

# # Make sure the secret is at least 30 characters and all random,
# # no regular words or you'll be exposed to dictionary attacks.
# # You can use `rake secret` to generate a secure secret key.

# # Make sure the secrets in this file are kept private
# # if you're sharing your code publicly.

# development:
#   secret_key_base: 4858ab29c43e063c5c6a311fdbdb5fb861e3092d919fd82512e78e3c75a82ca1571d6d344c2370425000006b3e286215d1e82f427e747f5c430fa681be38833e

# test:
#   secret_key_base: 52ac86b6fe8faa17fac89181438092f7e0e5c4c78bf22fa1121a0a541d3c4c0f71004ac04fc8d03511b9770e3c220ed5f17eaac7ee4fc01805c1eff3b91b2576

# # Do not keep production secrets in the repository,
# # instead read values from the environment.
# staging:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
